# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pull Request Workflow

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Pull Request Workflow
    runs-on: ubuntu-latest	
    # strategy:
    #   matrix:
    #     python-version: ["3.7", "3.8", "3.9", "3.10"]
    #     os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 coverage
    - name: Lint with flake8
      run: |
        flake8 .
      continue-on-error: true
    - name: Test with unittest
      run: |
        python3 -m unittest test/test_mathematical_operations.py
        python3 -m coverage run -m unittest
        python3 -m coverage report
